# Generated by Django 4.2.11 on 2024-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_age_alter_course_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
